// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: test.proto

package testservices

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	Foo(ctx context.Context, in *Foo, opts ...grpc.CallOption) (*Foo, error)
	StreamingFoo(ctx context.Context, opts ...grpc.CallOption) (TestService_StreamingFooClient, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) Foo(ctx context.Context, in *Foo, opts ...grpc.CallOption) (*Foo, error) {
	out := new(Foo)
	err := c.cc.Invoke(ctx, "/grpctunnel.testing.TestService/Foo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) StreamingFoo(ctx context.Context, opts ...grpc.CallOption) (TestService_StreamingFooClient, error) {
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[0], "/grpctunnel.testing.TestService/StreamingFoo", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceStreamingFooClient{stream}
	return x, nil
}

type TestService_StreamingFooClient interface {
	Send(*Foo) error
	Recv() (*Foo, error)
	grpc.ClientStream
}

type testServiceStreamingFooClient struct {
	grpc.ClientStream
}

func (x *testServiceStreamingFooClient) Send(m *Foo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testServiceStreamingFooClient) Recv() (*Foo, error) {
	m := new(Foo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility
type TestServiceServer interface {
	Foo(context.Context, *Foo) (*Foo, error)
	StreamingFoo(TestService_StreamingFooServer) error
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (UnimplementedTestServiceServer) Foo(context.Context, *Foo) (*Foo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Foo not implemented")
}
func (UnimplementedTestServiceServer) StreamingFoo(TestService_StreamingFooServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamingFoo not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_Foo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Foo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).Foo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctunnel.testing.TestService/Foo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).Foo(ctx, req.(*Foo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_StreamingFoo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).StreamingFoo(&testServiceStreamingFooServer{stream})
}

type TestService_StreamingFooServer interface {
	Send(*Foo) error
	Recv() (*Foo, error)
	grpc.ServerStream
}

type testServiceStreamingFooServer struct {
	grpc.ServerStream
}

func (x *testServiceStreamingFooServer) Send(m *Foo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testServiceStreamingFooServer) Recv() (*Foo, error) {
	m := new(Foo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpctunnel.testing.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Foo",
			Handler:    _TestService_Foo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingFoo",
			Handler:       _TestService_StreamingFoo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "test.proto",
}
